// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NestleWebApp.Models;

#nullable disable

namespace NestleWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NestleWebApp.Data.EMPLOYEE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("BU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GIFT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESULT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TIMEDRAW")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("EMPLOYEE");
                });

            modelBuilder.Entity("NestleWebApp.Data.LUCKYNUMBER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CONTENTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMAGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NUMB")
                        .HasColumnType("int");

                    b.Property<bool>("STATUS")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("LUCKYNUMBER");
                });
#pragma warning restore 612, 618
        }
    }
}
